name: Setup Terraform Templates

on:
  push:
    branches: [ "master" ]
  pull_request:

jobs:
  setup:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout main repo
      uses: actions/checkout@v2

    - name: Parse init.yaml
      id: parse
      run: |
        echo "TEMPLATE_REPO=$(cat init.yaml | grep template | cut -d ' ' -f2)" >> $GITHUB_ENV
        echo "APPNAME=$(cat init.yaml | grep APPNAME | cut -d ' ' -f2)" >> $GITHUB_ENV

    - name: Clone template repo
      run: git clone $TEMPLATE_REPO template-repo

    - name: Copy template files to main repo
      run: cp -r template-repo/* .

    - name: Replace parameters
      run: |
        find . -type f -exec sed -i "s/%%APPNAME%%/${APPNAME}/g" {} +

    - name: Set up Git for Push
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git remote add authenticated-origin https://x-access-token:${{ secrets.ACCESSTOKEN }}@github.com/pashishp/TerraFormTemplate.git
        git fetch authenticated-origin

    - name: Commit and push changes
      run: |
        git add .
        git commit -m "Setup Terraform Templates" || echo "No changes to commit"
        git push authenticated-origin HEAD:master

    # - name: Commit and create PR
    #   run: |
    #     git config --local user.email "pashishp2011@gmail.com"
    #     git config --local user.name "pashishp"
    #     git add -A
    #     git commit -m "Setup Terraform Templates" || echo "No changes to commit"
    #     git push https://${{secrets.ACCESSTOKEN}}@github.com/pashishp/TerraFormTemplate.git HEAD:master
    #     # Add more code as needed.  

